# Example for .streamlit/secrets.toml
# Uses TOML section [gcp_service_account] for safer, cleaner secret management.

[gcp_service_account]
type = "service_account"
project_id = "dev-project-id"
private_key_id = "fake-private-key-id"
private_key = "-----BEGIN PRIVATE KEY-----\nfake-key\n-----END PRIVATE KEY-----\n"
client_email = "dev-service-account@example.com"
client_id = "dev-client-id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/dev-service-account%40example.com"

google_api_key = "dev-google-api-key"
cse_id = "dev-cse-id"
cse_api_key = "dev-cse-api-key"
av_api_key = "dev-av-api-key"
gcs_bucket_name = "dev-bucket"
vertex_project_id = "dev-vertex-project"
vertex_location = "us-central1"
