# .streamlit/secrets.toml

# Google Cloud Service Account Credentials
# 1. Go to GCP -> IAM & Admin -> Service Accounts
# 2. Create a new service account
# 3. Grant it "Vertex AI User" and "Storage Object Admin" roles
# 4. Create a JSON key for it, download it.
# 5. Copy the *entire contents* of the JSON file and paste it here.
#    It must be enclosed in triple quotes """.
gcp_service_account = """
{
  "type": "service_account",
  "project_id": "YOUR-GCP-PROJECT-ID",
  "private_key_id": "...",
  "private_key": "-----BEGIN PRIVATE KEY-----\n...your-key-here...\n-----END PRIVATE KEY-----\n",
  "client_email": "your-service-account@your-project.iam.gserviceaccount.com",
  "client_id": "...",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "..."
}
"""

# Google Generative AI API Key (for LangChain)
# 1. Go to https://aistudio.google.com/app/apikey
google_api_key = "YOUR_GEMINI_API_KEY"

# Google Custom Search Engine (CSE)
# 1. Go to https://programmablesearchengine.google.com/
# 2. Create a new search engine.
# 3. Get the Search Engine ID (cx)
cse_id = "YOUR_CSE_ID"
# 4. Go to https://developers.google.com/custom-search/v1/overview
# 5. Click "Get a Key"
cse_api_key = "YOUR_CSE_API_KEY"

# Alpha Vantage API Key
# 1. Go to https://www.alphavantage.co/support/#api-key
av_api_key = "YOUR_ALPHA_VANTAGE_API_KEY"

# Your GCS Bucket Name
# (The bucket your service account has "Storage Object Admin" on)
gcs_bucket_name = "your-unique-gcs-bucket-name"

# Your Vertex AI Project ID and Location
vertex_project_id = "YOUR-GCP-PROJECT-ID"
vertex_location = "us-central1"